project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning Blogs"
  repo-url: https://github.com/Md-Shahedul-Haque/MachineLearningBlogs
  repo-actions: [source]
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Md-Shahedul-Haque/MachineLearningBlogs
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://www.linkedin.com/in/md-shahedul-haque-shawon-5023491b7/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

